disabled_rules:
 - identifier_name
 - trailing_whitespace
 - function_parameter_count
 - trailing_comma
 - cyclomatic_complexity
 - closure_parameter_position

excluded:
 - .git
 - images
 - VisualMan.xcodeproj
